### ISSUE TITLE
Barra de interesse não funfa

### ISSUE THREAD

**Issue by DaviPx** [carlosdamazio/UniCEUB---Dev_web#19]
SO FRONT END
E ODEIO BAQ END
VCS GOSTA DE CONFIGURA SERVIDOR
VCS GOSTA DE PHP
@carlosdamazio  ASSASINO DE HTML
BUG OCORRE NADA ACONTECE 
CAFE COM CODIGO

**Comment by carlosdamazio** [comment]
CALM THE FUCK DOWN.
Irei fazer o trêm funcionar amanhã de noite.

**Comment by carlosdamazio** [comment]
Resolvido.
